config/routes.rb
Rails.application.routes.draw do
  root to: 'artists#index'
  resources :artists do
    resources :songs, only: [:new, :create]
  end

  resources :songs, only: [:show]
  resources :playlists

  get '/auth/spotify/callback', to: 'sessions#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :songs

  validates :name, presence: true, uniqueness: true
  validates :image_path, presence: true
  validates_associated :songs
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  has_many :playlist_songs
  has_many :songs, through: :playlist_songs

  validates :name, presence: true, uniqueness: true
  validates_associated :playlist_songs
  validates_associated :songs
end

app/models/playlist_song.rb
class PlaylistSong < ApplicationRecord
  belongs_to :playlist
  belongs_to :song
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_many :playlists

  validates :title, presence: true, uniqueness: true
  validates :artist_id, presence: true

  validates_associated :playlists

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :destroy, :update]

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def create
    @artist = Artist.new(artist_params)
    if @artist.save
      redirect_to artist_path(@artist)
    else
      render :new
    end
  end

  def update
    if @artist.update(artist_params)
      flash.notice = "Artist # #{@artist.name} has been updated!"
      redirect_to artist_path(@artist)
    else
      render :edit
    end
  end

  def destroy
    @artist.destroy

    redirect_to artists_path
  end

  private

  def artist_params
    params.require(:artist).permit(:name, :image_path)
  end

  def set_artist
    @artist = Artist.find(params[:id])
  end
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :all_songs, only: [:show, :new, :edit]
  before_action :set_playlist, only: [:show, :edit, :update]

  def index
    @playlists = Playlist.all
  end

  def show
  end

  def new
    @playlist = Playlist.new
  end

  def create
    @playlist = Playlist.create(playlist_params)
    redirect_to @playlist
  end

  def edit
  end

  def update
    if @playlist.update(playlist_params)
      redirect_to playlist_path(@playlist)
    else
      render :edit
    end
  end

  private

  def playlist_params
    params.require(:playlist).permit(:name, song_ids: [])
  end

  def all_songs
    @songs = Song.all
  end

  def set_playlist
    @playlist = Playlist.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    byebug
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit]
  before_action :set_artist, only: [:new, :create]
  def index
    @songs = Songs.all
  end

  def new
    @song = @artist.songs.new
  end

  def create
    @artist = Artist.find(params[:artist_id])
    @song = @artist.songs.new(song_params)
    if @song.save
      redirect_to song_path(@song)
    else
      render :new
    end
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist_id)
  end

  def set_song
    @song = Song.find(params[:id])
  end

  def set_artist
    @artist = Artist.find(params[:artist_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>
  <%= render partial: "shared/errors", locals: { target: @artist } %>

  <%= f.label :name %>
  <%= f.text_area :name %><br /><br />

  <%= f.label :image_path %>
  <%= f.text_area :image_path %><br /><br />

  <h3><%= f.submit %></h3>
<% end %>

app/views/artists/edit.html.erb
<h1>Edit Artist <%= @artist.name %></h1>

<%= render partial: "form" %>

app/views/artists/index.html.erb
<h1>Artists</h1>
<p><%= link_to "New Artist", new_artist_path %></p>

<ul>
  <% @artists.each do |artist| %>
    <li><%= link_to artist.name, artist_path(artist) %></li>
  <% end %>
</ul>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render partial: "form" %>

app/views/artists/show.html.erb
<h1>Artist</h1>
<h2><%= @artist.name %></h2>
<%= image_tag(@artist.image_path, :alt => "artist image") %>
<ul>
  <% @artist.songs.each do |song| %>
    <li><%= song.title %></li>
  <% end %>
</ul>
<h4><%= link_to "New Song", new_artist_song_path(@artist) %></h4>
<p><%= link_to "Edit", edit_artist_path(@artist) %></p>
<p><%= link_to "Delete", artist_path(@artist), method: :delete %></p>
<p><%= link_to "Back to Artists", artists_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MixMaster</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>

    <%= link_to "Sign in with Spotify", "/auth/spotify" %>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_for(@playlist) do |f| %>
  <%= render partial: "shared/errors", locals: { target: @playlist } %>

  <%= f.text_field :name%>

  <% @songs.each do |song| -%>
    <div class="">
      <%= check_box_tag(:song_ids, song.id, @playlist.songs.include?(song), :name => 'playlist[song_ids][]', id: "song-#{song.id}") %>
      <%= song.title %>
    </div>
  <% end %>

  <%= f.submit %>
<% end %>

app/views/playlists/edit.html.erb
<h1>Edit Playlist <%= @playlist.name %></h1>

<%= render partial: "form" %>

app/views/playlists/index.html.erb
<h1>All Playlists</h1>

<p><%= link_to "New playlist", new_playlist_path %></p>

<ul>
  <% @playlists.each do |playlist| %>
    <li><%= link_to playlist.name, playlist_path(playlist) %></li>
</ul>
  <% end %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render partial: "form" %>

app/views/playlists/show.html.erb
<h1>Playlist <%= @playlist.name %></h1>

<ul>
  <% @songs.each do |song| %>
    <% if @playlist.songs.include?(song) %>
      <li><%= link_to song.artist.name, artist_path(song.artist) %></li>
      <li><%= link_to song.title, song_path(song) %></li>
    <% end %>
  <% end %>
</ul>

<p><%= link_to "Delete", playlist_path(@playlist), method: :delete %></p>
<p><%= link_to "Edit", edit_playlist_path %></p>

app/views/shared/_errors.html.erb
<% if target.errors.any? %>
  <h2><%= pluralize(target.errors.count, "error") %> prohibited this record from being saved:</h2>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/songs/new.html.erb
<h1>New Song</h1>
<p>Add a new song for <%= @artist.name %></p>

<%= form_for ([@artist, @song]) do |f| %>
  <%= f.label :title, "Song Title" %>
  <%= f.text_field :title %><br />

  <%= f.submit "Create Song" %>
<% end %>

app/views/songs/show.html.erb
<h1>Song :<%= @song.title %></h1>
<h2>Artist:<%= link_to @song.artist.name, artist_path(@song.artist) %></h2>